### ISSUE TITLE
Compile error: template argument deduction/substitution failed + optic flow node crashing

### ISSUE THREAD

**Issue by douwecorel** [apollack11/advanced-computer-vision#2]
When I compile this package using catkin_make within my workspace I get the following compile error:

/usr/include/opencv2/core/operations.hpp:1850:51: note:   template argument deduction/substitution failed:
/home/stagiair/catkin_ws_2/src/advanced-computer-vision-master/src/flow.cpp:559:58: note:   cannot convert ‘((FlowCalculator*)this)->FlowCalculator::H’ (type ‘cv::Matx33d {aka cv::Matx<double, 3, 3>}’) to type ‘double’
       motion_avg += Point3f((H * Mat(*it2) - H * Mat(*it1)) / N); // you can tell it's the average by the way that it is!

Is this a known problem? And if so, is there a solution available? 

Thanks in advance!

**Comment by njkaiser** [comment]
This has not been an issue in the past - can you post your Linux distro and OpenCV version?

**Comment by douwecorel** [comment]
I am using Ubuntu 14.04 LTS. I will have to check my opencv version. I am currently on the road so I will be able to provide the information in a couple of hours. 

My goal is to check whether I can use optical flow odometry for a school project indoor SLAM application. Sinds you seem to have been able to implement this perhaps you could advice me on this topic. I can not use wheel odometry in this project and the robot is an AGV that runs with ROS. I do have an IMU. What would be the best way for me to approach this?

**Comment by douwecorel** [comment]
My OpenCV version is 2.4.8

**Comment by njkaiser** [comment]
Linux distro / OpenCV version should both be fine, this is an odd one. Did you change the code in any way? If not, can you try printing out what values and types **all** of the variables going into the `Point3f` constructor on that line are? The quantity `H * Mat(*it1)` and `H * Mat(*it2)` are of special interest, since `Mat(*it1)`/`Mat(*it2)` should be multiplyable by type `H`, but for some reason it looks like that multiplication is failing. If that's true, it will fail to compile your print line, too.

**Comment by douwecorel** [comment]
I managed to fix the previous issue by reinstalling my opencv. Also installed the contrib variant and maybe that had something to do with it. 

On another note, when I try to launch your project.launch and try to make it subscribe to a gazebo camera topic for the optical flow node, the node dies without any notification of an error or something. So building the project was successful but now I am facing this issue. Have you already tried running this package with a Gazebo simulation?

**Comment by njkaiser** [comment]
I've not tried it with Gazebo, but that shouldn't matter as long as you give it a camera feed with the correct size, encoding, etc. The code has quite a few hard-coded parameters in it (image size, for example) that might not work out of the box with your setup, so you'll need to step through the code, check where it's failing, and go from there.

**Comment by douwecorel** [comment]
Thank you for your fast reply!

I have been able to debug where the code seems to have problems with my application and this seems to be in the constructor part where a couple of cv::Mat objects are created. If I comment this part of the code out, the node does not die. The lines are the lines below the comment 

> //hack these for now since can't initialize the way I want to (stupid pre-c++11!)

Perhaps I need to tune these parameters in order for the package to work with my setup? Could you perhaps indicate how I should do that? It would help me a lot and I would really appreciate it :)

Thanks a lot for the help so far!

**Comment by njkaiser** [comment]
If you can nail down exactly which of those lines fails, then you've found your problem, haven't you? I'm a little surprised commenting them out works, since the rest of the code would then be using uninitialized memory.

And yes, you **definitely** need to tune *all* of the parameters. `camera_matrix`, `distortion_coefficients`, and pretty much every other hard-coded value in the code are *all* specific to your setup and camera. If you don't know what they should be I'm afraid you're going to have to do quite a bit of reading on the subject to get a grasp of what each line of the code is doing before you'll understand why it's failing.

**Comment by douwecorel** [comment]
That is odd then indeed. Because at that point it should give some undefined references I would say? I will look into it. But in the meantime, maybe it will give me some useful testing results if I can copy your setup parameters. So if you could tell me what the specifications are in your setup. So I can try and setup my simulation in the same way and use the standard hard coded parameters. 

Another question that comes up is how much can camera's differ apart from the image resolution, size etc. I can understand that the algorithm might not give optimal results when certain parameters are not tuned correctly, but in order for the algorithm to process the input image and not crash it should only be a matter of getting the right input image format into the algorithm right? 

I just came up to this [webpage](https://docs.opencv.org/2.4/modules/calib3d/doc/camera_calibration_and_3d_reconstruction.html#double%20calibrateCamera(InputArrayOfArrays%20objectPoints,%20InputArrayOfArrays%20imagePoints,%20Size%20imageSize,%20InputOutputArray%20cameraMatrix,%20InputOutputArray%20distCoeffs,%20OutputArrayOfArrays%20rvecs,%20OutputArrayOfArrays%20tvecs,%20int%20flags,%20TermCriteria%20criteria)) from OpenCV. Shouldn't it be possible to use some of these functions to calculate some of the hard coded matrices that are in the constructor? Would that perhaps give me the parameters I need in order for the package to work?

**Comment by njkaiser** [comment]
This conversation is taking a pretty big leap away from the original issue, which you mentioned you've already fixed. Let's chat offline about this other stuff, since it's almost certainly not a code issue anymore, and I can try to help you through it. Please send me an email at nathanielkaiser2017@u.northwestern.edu and we can work from there.
