### ISSUE TITLE
Flow node does not publish any data to the topics.

### ISSUE THREAD

**Issue by mdurmuss** [apollack11/advanced-computer-vision#3]
Hi,
I try to run **project.launch** file. Everything looks fine and in my opinion flow node is waiting for the image from **"/usb_cam/image_raw/compressed"** topic. But when I publish my images to that topic, flow node is still doing nothing. Can you tell me what I am doing wrong?

**Comment by njkaiser** [comment]
I think you just need to publish to `/usb_cam/image_raw`, and not `/usb_cam/image_raw/compressed`, as the "compressed" part is just hinting to the subscriber that this is a compressed topic (see [this line](https://github.com/apollack11/advanced-computer-vision/blob/master/src/flow.cpp#L126)).

You can easily test this by putting a simple print statement in the callback, and seeing if it fires when you publish to either of those two topic names.

However, it's been a _very_ long time since I've touched this code (or ROS in general), so bear with me if I'm a little rusty :)
